services:
  - type: web
    name: dscpl-spiritual-companion
    env: python
    plan: free
    buildCommand: |
      mkdir -p backend/src/static
      cd frontend && npm install -g pnpm && pnpm install && pnpm run build
      cp -r dist/* ../backend/src/static/
    startCommand: cd backend && python3.11 src/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GOOGLE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SECRET_KEY
        generateValue: true 